apiVersion: projects.gitlab.crossplane.io/v1alpha1
kind: AccessToken
metadata:
  name: example-access-token
spec:
  forProvider:
    accessLevel: 40
    expiresAt: 2024-03-15T08:00:00Z
    name: example-access-token
    projectIdRef:
      name: example-project-demo
    scopes:
      - read_repository
  providerConfigRef:
    name: gitlab-provider
  writeConnectionSecretToRef:
    name: gitlab-example-access-token
    namespace: crossplane-system