apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Group
metadata:
  name: example-group-demo
spec:
  forProvider:
    description: example group description
    name: Example Group Demo
    path: example_group_demo
  providerConfigRef:
    name: gitlab-provider
  writeConnectionSecretToRef:
    name: gitlab-group-example-group
    namespace: crossplane-system