apiVersion: github.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: github-provider-config
spec:
  credentials:
    source: Secret
    secretRef:
      name: github-provider-secret
      namespace: crossplane-system
      key: credentials
